//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityHRApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Id { get; set; }
        public Nullable<int> EdInstitutionId { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public string TypeOfDocument { get; set; }
        public string YearOfGraduation { get; set; }
    
        public virtual EducationalInstitution EducationalInstitution { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
