//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityHRApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentRecord
    {
        public int Id { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<System.DateTime> DateOfTheOrder { get; set; }
        public string OrderNumber { get; set; }
        public string IncentivesAndPenalties { get; set; }
        public Nullable<System.DateTime> DateOfEmployment { get; set; }
        public Nullable<System.DateTime> DateOfDismissal { get; set; }
        public string ReasonForDismissal { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Position Position { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
