//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityHRApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversituHREntities : DbContext
    {
        private static UniversituHREntities _context;

        public UniversituHREntities()
            : base("name=UniversituHREntities")
        {
        }

        public static UniversituHREntities GetContext()
        {
            if (_context == null) { _context = new UniversituHREntities(); }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicDegree> AcademicDegree { get; set; }
        public virtual DbSet<AcademicTitle> AcademicTitle { get; set; }
        public virtual DbSet<Coutry> Coutry { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<EducationalInstitution> EducationalInstitution { get; set; }
        public virtual DbSet<EmploymentRecord> EmploymentRecord { get; set; }
        public virtual DbSet<Objects> Objects { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Settlement> Settlement { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersObjects> UsersObjects { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
