//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityHRApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Education = new HashSet<Education>();
            this.EmploymentRecord = new HashSet<EmploymentRecord>();
        }
    
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> SettlementId { get; set; }
        public Nullable<int> StreetId { get; set; }
        public string House { get; set; }
        public Nullable<int> Flat { get; set; }
        public byte[] Photo { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> AcademicDegreeId { get; set; }
        public Nullable<int> AcademicTitleId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<long> PassportNumber { get; set; }
        public Nullable<System.DateTime> DateOfIssuePassport { get; set; }
        public string WhoIssuedPassport { get; set; }
        public Nullable<long> Telephone { get; set; }
    
        public virtual AcademicDegree AcademicDegree { get; set; }
        public virtual AcademicTitle AcademicTitle { get; set; }
        public virtual Coutry Coutry { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentRecord> EmploymentRecord { get; set; }
        public virtual Position Position { get; set; }
        public virtual Region Region { get; set; }
        public virtual Settlement Settlement { get; set; }
        public virtual Street Street { get; set; }
    }
}
